TAKING ME
[{u'calltype': u'amd64', u'realsz': 337, u'diff': u'NEW', u'name': u'main', u'cc': 4, u'indegree': 0, u'nargs': 0, u'difftype': u'new', u'edges': 13, u'outdegree': 10, u'nlocals': 10, u'cost': 116, u'datarefs': [1, 6336768, 4230213, 4230180, 1, 60000, 4230183, 128, 4221920, 4230207], u'callrefs': [{u'type': u'C', u'addr': 4222496, u'at': 4222087}, {u'type': u'C', u'addr': 4222352, u'at': 4222333}, {u'type': u'C', u'addr': 4221584, u'at': 4222367}, {u'type': u'C', u'addr': 4222384, u'at': 4222130}, {u'type': u'J', u'addr': 4222152, u'at': 4222139}, {u'type': u'C', u'addr': 4221280, u'at': 4222184}, {u'type': u'C', u'addr': 4222464, u'at': 4222147}, {u'type': u'C', u'addr': 4221232, u'at': 4222218}, {u'type': u'C', u'addr': 4221472, u'at': 4222244}, {u'type': u'J', u'addr': 4222311, u'at': 4222260}, {u'type': u'C', u'addr': 4221232, u'at': 4222298}, {u'type': u'C', u'addr': 4222480, u'at': 4222306}], u'offset': 4222032, u'ebbs': 2, u'nbbs': 11, u'type': u'sym', u'size': 350}]
ERR. Target function sym.main0 does not match main
Failed to patch all expected patches: 6  total patched: 12
