TAKING ME
[{u'calltype': u'amd64', u'realsz': 427, u'diff': u'NEW', u'name': u'sym.get_image', u'outdegree': 15, u'cc': 4, u'indegree': 1, u'dataxrefs': [], u'nargs': 0, u'codexrefs': [{u'type': u'C', u'addr': 4231196, u'at': 4230832}], u'edges': 10, u'difftype': u'new', u'nlocals': 16, u'cost': 145, u'datarefs': [4282242, 6394208, 4282312, 80, 53], u'callrefs': [{u'type': u'C', u'addr': 4273024, u'at': 4230898}, {u'type': u'C', u'addr': 4273024, u'at': 4230939}, {u'type': u'C', u'addr': 4229168, u'at': 4230968}, {u'type': u'C', u'addr': 4231216, u'at': 4231196}, {u'type': u'C', u'addr': 4231344, u'at': 4231205}, {u'type': u'C', u'addr': 4229488, u'at': 4231247}, {u'type': u'C', u'addr': 4229312, u'at': 4230990}, {u'type': u'C', u'addr': 4229312, u'at': 4231005}, {u'type': u'C', u'addr': 4231280, u'at': 4231187}, {u'type': u'C', u'addr': 4230176, u'at': 4231046}, {u'type': u'C', u'addr': 4230176, u'at': 4231061}, {u'type': u'C', u'addr': 4230176, u'at': 4231076}, {u'type': u'C', u'addr': 4229152, u'at': 4231102}, {u'type': u'C', u'addr': 4229360, u'at': 4231148}, {u'type': u'C', u'addr': 4231408, u'at': 4231162}], u'offset': 4230832, u'ebbs': 2, u'nbbs': 8, u'type': u'sym', u'size': 427}]
ERR. Target function sym.get_image0 does not match sym.get_image
Failed to patch all expected patches: 108  total patched: 216
