TAKING ME
[{u'calltype': u'amd64', u'realsz': 353, u'diff': u'NEW', u'name': u'sym.main', u'outdegree': 11, u'cc': 3, u'indegree': 1, u'dataxrefs': [], u'nargs': 0, u'codexrefs': [{u'type': u'C', u'addr': 4223309, u'at': 4222992}], u'edges': 7, u'difftype': u'new', u'nlocals': 20, u'cost': 100, u'datarefs': [6341424, 2000, 4234384], u'callrefs': [{u'type': u'C', u'addr': 4226672, u'at': 4223037}, {u'type': u'C', u'addr': 4226672, u'at': 4223078}, {u'type': u'C', u'addr': 4226672, u'at': 4223119}, {u'type': u'C', u'addr': 4226672, u'at': 4223160}, {u'type': u'C', u'addr': 4226672, u'at': 4223201}, {u'type': u'C', u'addr': 4226672, u'at': 4223242}, {u'type': u'C', u'addr': 4222448, u'at': 4223286}, {u'type': u'C', u'addr': 4223328, u'at': 4223309}, {u'type': u'C', u'addr': 4222608, u'at': 4223334}, {u'type': u'C', u'addr': 4223360, u'at': 4223267}, {u'type': u'C', u'addr': 4223456, u'at': 4223304}], u'offset': 4222992, u'ebbs': 1, u'nbbs': 6, u'type': u'sym', u'size': 357}]
ERR. Target function sym.main0 does not match sym.main
Failed to patch all expected patches: 36  total patched: 72
